services:
  frontend:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: react-19-fe-prod
    ports:
      - "3000:80"
      - "443:443"
    restart: unless-stopped